use proyecto;
set foreign_key_checks = 0;
truncate table addresses;
truncate table brands;
truncate table brands_categories;
truncate table cart_items;
truncate table categories;
truncate table countries;
truncate table customers;
truncate table order_details;
truncate table order_track;
truncate table orders;
truncate table product_details;
truncate table product_images;
truncate table products;
truncate table shipping_rates;
truncate table states;
set foreign_key_checks = 1;